name: ubergrass
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^2.3.1
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.2

  numberpicker: ^2.1.1

  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.12
  cloud_functions: ^3.2.12
  firebase_auth: ^3.3.14

  google_api_headers: ^1.2.0+1
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_maps_flutter: ^2.1.1
  flutter_google_places: ^0.3.0

  flutter_polyline_points: ^1.0.0
  geocoding: ^2.0.4


  http: ^0.13.4
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
