// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqvXF5_PUgCBs4OwHX4mAAs4JuZryqcUE',
    appId: '1:884039774251:web:e11fcd6d6b6626a86f3a6e',
    messagingSenderId: '884039774251',
    projectId: 'flutter-iii-358df',
    authDomain: 'flutter-iii-358df.firebaseapp.com',
    storageBucket: 'flutter-iii-358df.appspot.com',
    measurementId: 'G-JHJ26MQZ3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmppdu0c4srz_8JHuW5A0C7b9k00iDGAM',
    appId: '1:884039774251:android:19dda021ea9ca2d76f3a6e',
    messagingSenderId: '884039774251',
    projectId: 'flutter-iii-358df',
    storageBucket: 'flutter-iii-358df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf1qb-9W_Gw-oT9w4iprlaTC0xD7zmMRY',
    appId: '1:884039774251:ios:0203ad9a025fc1df6f3a6e',
    messagingSenderId: '884039774251',
    projectId: 'flutter-iii-358df',
    storageBucket: 'flutter-iii-358df.appspot.com',
    androidClientId: '884039774251-k6fmifoihuc0js7bidp202vhdgvib43h.apps.googleusercontent.com',
    iosClientId: '884039774251-t7jqg0e5vi0rr2d7dapc1loevb8j4hiu.apps.googleusercontent.com',
    iosBundleId: 'com.salemcorp.ubergrass',
  );
}
